sudo: required
services:
  - docker
before_install:
- docker pull azuresdk/ci-slave-dnx
- docker run -d -p 127.0.0.1:80:4567 azuresdk/ci-slave-dnx /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run azuresdk/ci-slave-dnx /bin/sh -c "cd /root/sinatra; bundle exec rake test"
script:
- cd src/CLU
- dnu restore