language: csharp
sudo: required
dist: trusty
env:
  - MONO_THREADS_PER_CPU=2000
mono:
  - 4.0.5
os:
  - linux
  - osx
env:
  - DNX_VERSION=1.0.0-rc1-final
  - DNX_USER_HOME=/opt/dnx
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - jq    
install:
  - curl https://azurecludrops.blob.core.windows.net/drops/ubuntu.14.04-x64.latest.tar.gz  | tar xvz && chmod +x ubuntu.14.04-x64/clurun ubuntu.14.04-x64/az
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
script:
  - dnvm install $DNX_VERSION -r coreclr -alias default
  - dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default
  - cd src/CLU
  - dnu restore
  - cd Commands.Common.ScenarioTest
  - dnx test